site_name: SpykeTools
repo_url: https://github.com/bsotomayorg/Spyke-Tools
#copyright: Boris Sotomayor Gomez
nav:
    - Home: index.md
    - About: about.md
    #- Usage:
    #    - Quick start: quick_start.md
    - Tutorials:
        - Computation of distances between two spike trains:
            - Single Neuron distances: notebooks/single_neuron_distances.ipynb
        - Integration of Neurodata Without Borders (NWB) format:
            - Data Analysis of Allen Brain Institute dataset (NWB): notebooks/NWB_data_analysis_tutorial.ipynb
        - Computation of distances for Neural Ensembles:
            #- Neural Ensembles Computation of distances: notebooks/NeuralEnsembles_distances.ipynb
            - Parallel computing of pairwise distances: notebooks/NeuralEnsembles_pairwise_distances.ipynb
        - Decoding performance:
            - Clustering performance: notebooks/clustering_performance.ipynb
        - Visualization:
            - Raster plots: notebooks/visualization_tutorial.ipynb
        #- Multi-core options:
        #   - Selecting amount of CPU-cores for running parallel jobs
        #                                                             
    - API:
        - IO:
            #- Test: io.Test.md
            - Handling neuronal data in NWB format: io.DataManager.md
        - Distances:
            - 1. Victor-Purpura (VP) distance: distances.victor_purpura.md
            - 2. Inter-Spike Interval (ISI) distance: distances.ISI.md
            - 3. SPIKE distance: distances.SPIKE.md
            - 4. Rate-Independent SPIKE (RI-SPIKE) distance: distances.RISPIKE.md
            - 5. SpikeShip distance: distances.spikeship.md
        - Manifold learning algorithms: 
            - 1. 2D T-distributed Stochastic Neighbor Embedding (t-SNE): manifold.tsne.md
            - 2. 2D Uniform Manifold Approximation and Projection for Dimension Reduction (UMAP): manifold.umap.md
        - Clustering performance:
            - 1. Adjusted Rand Index (ARI): clustering.ARI_score.md
            - 2. Silhouette score: clustering.silhouette_score.md
            - 3. Discriminability Index (DI): clustering.discriminability_index.md
        - Visualization:
            - 1. Raster plots: vis.raster.md
        - Pre-processed datasets: datasets.load_allen_brain_ds.md
    - Citing: citing.md
theme: 
    name: material
    palette:
        primary: deep purple
        accent: deep purple
    features:
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - search.highlight
        - search.suggest
        - toc.follow
        - content.tabs.link
plugins:
    - mkdocs-jupyter:
        ignore_h1_titles: True
    - search
    - mkdocstrings
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - admonition
    - pymdownx.details
    - footnotes